### ISSUE TITLE
Hemlock leaves inconsistencies

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Terrestria#169]
There seems to be something different about terrestria:hemlock_leaves:
- fast leaf decay mods don't seem to work on them
- They aren't made passable by a mod (eg Tiny Tweaks), unlike other leaves
- When looking through the leaves, the leaves behind them in a straight line look invisible.

**Comment by Linguardium** [comment]
the extended leaves in the terraformers mods do not extend LeavesBlock and thus authors of the interacting mods (tinytweaks, fastleafedecay,etc) must add compatibility with them to their mods for their mods to work. 
for example, using the leaf blocktag instead of instanceof LeavesBlock should work fine.

as for the third block, no idea, i'll let the mod devs answer that :P

**Comment by Prospector** [comment]
Mods should really use the leaves tag for identifying leaves, rather than checking if it's an instance of LeavesBlock. If something leaves-specific is needed, specific compat will have to be added, as our Extended Leaves would break assumptions made in the LeavesBlock class.

For the third point, that is Terrestria's optileaves option, which is on by default. If you want the vanilla look, optileaves can be turned off in the terrestria client config file. (Do note, performance could be significantly worse due to high leaves density in certain biomes)..

**Comment by ghost** [comment]
Thanks for the reply.  I'll contact other mod makers about checking for the leaves tag instead of an instance of LeavesBlock.  At least the ones that update to 1.16.2 and can't handle Hemlock leaves.

**Comment by Prospector** [comment]
Unfortunately I have no idea when the Terraformers mods will make it to 1.16.2. It could be a very long time, the update is quite a disaster for us. I personally do not have any plans to update Traverse past 1.16.1 due to a lack of interest as I'm currently happy playing on 1.16.1. However, I am not fully in the loop about what the rest of the Terraformers' plans are, as I have been taking a bit of a break.

**Comment by ghost** [comment]
When it comes down to it, I'll let the players on my server decide if they'd like to stay on 1.16.1 or do a world reset for 1.16.2.  I'm very grateful for all the enjoyment your mods have given us (and still do!), and wish you all the best!  And on a personal note, I think campanion is a stroke of genius.
