### ISSUE TITLE
Desert Villagers kill themselves on tiny cacti

### ISSUE THREAD

**Issue by yorii** [TerraformersMC/Terrestria#202]
They don't really seem to understand they shouldn't be walking straight into these and dying for no reason.

**Comment by saltyseadoggo** [comment]
This is also an issue with desert rabbits, as well as nighttime monsters.~

**Comment by coderbot16** [comment]
This should have been fixed in the 1.16.3 version. If you're using Lithium, try removing it temporarily and see if the issue persists.

**Comment by saltyseadoggo** [comment]
I've finally gotten around to testing this. In the setups in the screenshot below, none of the mobs ever run into the tiny cactus; the villager won't even attempt to walk to the bed. This was tested with Lithium installed. I'm not sure what I saw before, if this is the case...
![2020-12-09_19 23 16](https://user-images.githubusercontent.com/69029346/101717652-923bf980-3a54-11eb-8f8a-ed047449f7d4.png)

**Comment by coderbot16** [comment]
Since this was supposed to be fixed in the 1.16.2/1.16.3 stable release, it's possible that this was observed on an outdated version of the mod or an outdated version of Lithium (both need to be updated if you're running both of them). I'm pretty sure that this should be resolved, however if you observe it happening again feel free to let me known and I'll reopen the issue.
