### ISSUE TITLE
Missing Color Providers

### ISSUE THREAD

**Issue by CoolMineman** [TerraformersMC/Terrestria#252]
DARK_JAPANESE_MAPLE_LEAVES, JUNGLE_PALM_LEAVES, and maybe some other things are missing color providers.
https://github.com/TerraformersMC/Terrestria/blob/1.16.3/src/main/java/com/terraformersmc/terrestria/TerrestriaClient.java#L51-L62
Causes CoolMineman/BitsAndChisels#26

**Comment by coderbot16** [comment]
I suppose that it would be possible to register a default color provider here, since the colors for those leaves are baked into the texture.

But the Bits and Chisels code [there](https://github.com/CoolMineman/BitsAndChisels/blob/master/src/main/java/io/github/coolmineman/bitsandchisels/BitsBlockEntity.java#L175) is broken - you should be using the vanilla `BlockColors` class instead, since it's not guaranteed that all colored blocks will exist in Fabric's `ColorProviderRegistry`.

**Comment by CoolMineman** [comment]
Switched to `BlockColors` in B&C
