### ISSUE TITLE
Feature order cycle crash between minecraft and terrestria

### ISSUE THREAD

**Issue by IJuanTM** [TerraformersMC/Terrestria#329]
Hi, I am trying to generate a new (superflat) world, but it keeps crashing with the following error:

`java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:snowy_taiga]=net.minecraft.class_1959@731e97ba}, Reference{ResourceKey[minecraft:worldgen/biome / terrestria:windswept_redwood_forest]=net.minecraft.class_1959@45416f1e}]`

Seems to be minecraft:snowy_taiga everytime but the terrestria biome seems to differ from crash to crash, have seen redwood_forest and windswept_redwood_forest.

Full crash report: https://mclo.gs/dlZjcrz
Latest log: https://mclo.gs/ge9OnOx

Does anyone know how to fix this? Thanks in advance!

**Comment by gniftygnome** [comment]
Terrestria 6.0.13 on Fabric Minecraft 1.20.1.  Very high mod count.

I'm not sure about reproducing this just because of the sheer number of mods that add or modify biomes.  Terrestria for 1.20.1 has extensive testing with vanilla and with other big biome mods like BYG, Regions Unexplored, Terralith, etc., so I am fairly certain this is not actually *caused* by Terrestria.  It's probably basically a drive-by by one of the smaller mods.  Unfortunately, thanks to Mojang's poor design for the biome feature cycle loop detection, the logs do not give nearly enough information to debug without trial and error.  The cycle almost certainly involves Minecraft, Terrestria, and at least one other biome mod (maybe more).

If you would like to help, acquiring another log with the Cyanide mod installed can be very useful:
https://modrinth.com/mod/cyanide

(However, the log provided is huge and seems to be incomplete, probably because of the size, so this may depend on whether the output from Cyanide makes it into the log...)

**Comment by IJuanTM** [comment]
> It's probably basically a drive-by by one of the smaller mods.

Makes sense, I tried removing any of the other mods that adds or changes biomes, but still kept getting this error. I have since dropped this modpack and started making another, hopefully with less issues.

Thans for the tip about the cyanide mod, could definitely help!
