### ISSUE TITLE
Lava + water = basalt

### ISSUE THREAD

**Issue by dranorter** [TerraformersMC/Terrestria#50]
Since this mod adds basalt, it would make sense for lava to generate basalt instead of stone when exposed to water. (Of course source blocks still would make obsidian.) That way, when lava flows from a volcano into the ocean, the generated stone would match the surroundings.

**Comment by NeusFear** [comment]
I like the idea of having paths on the basalt dirt stuff, we can probably make that happen.
However, I don't think changing the stone/cobblestone formation to basalt is something that we would do, simply just because it directly modifies a core vanilla feature, and we're focusing on adding features or extending them to other areas. However it is a decent idea and we may talk about it, and make it a config option. Don't bet on it though lol

**Comment by coderbot16** [comment]
Fixed in dev, will be pushed out in the next patch.
