### ISSUE TITLE
Suggestion for volcano islands

### ISSUE THREAD

**Issue by steelborngaming** [TerraformersMC/Terrestria#76]
The volcanoes that spawn on the biome seem a bit puny I was wondering what you guys thought about it having bigger beefier but fewer volcanoes.

**Comment by NeusFear** [comment]
You may have just gotten unlucky because the volcanoes that generate are actually quite large, but small ones also generate to support the large ones. I obviously can’t see your world, but if you send a screenshot of the “small” volcanoes I can better understand or rather tell you if they’re the big ones or small ones.

**Comment by coderbot16** [comment]
The structure system is somewhat luck based, some volcanic islands have *no* huge volcanoes and some have 3-4 massive volcanoes. Check some other islands to make sure that you weren't just unlucky.
